### ISSUE TITLE
Use “camel case” in your classes.

### ISSUE THREAD

**Issue by jpochetedmead** [atmelaku/adventure-game#3]
> Classes should use “camel case”, as in SuperGoldFactory rather than “underscore format” as in super_gold_factory.

`class numbers(object):` should be: `class Numbers(object):`

https://github.com/atmelaku/adventure-game/blob/b25e9d37c2fcf5d82590ab12359b85f9a26572cb/math1.py#L4

**Comment by atmelaku** [comment]
the class name just numbers which is one word and it could start with capital letter but some gave me  a feedback for that.

**Comment by atmelaku** [comment]
the class name just numbers which is one word and it could start with capital letter but some gave me a feedback for that
